language: java
jdk:
  - openjdk11

# Git Push할 Branch
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x ./gradlew
script: "./gradlew clean build"

before_deploy:
  - zip -r SPAbootVue *
  - mkdir -p deploy
  - mv SPAbootVue.zip deploy/SPAbootVue.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-deploy3036 # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Lee-ChangHee/SPAbootVue #Github 주소
      branch: master

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: springboot-deploy3036 # 생성한 S3 버킷
      key: SPAbootVue.zip # S3 버킷에 저장된 jaewon-study.zip 파일을 EC2로 배포
      bundle_type: zip
      application: springCodeDeploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: springCodedeployApplication # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: Lee-ChangHee/SPAbootVue #Github 주소
        branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - chbe5082@Naver.com