language: java
jdk:
  - openjdk11

# Git Push할 Branch
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv SPAbootVue.zip deploy/SPAbootVue.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-deploy3036 # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Lee-ChangHee/SPAbootVue #Github 주소
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - chbe5082@Naver.com