spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    use-legacy-processing: true

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8080

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

---
spring.profiles: set2
spring.profiles.include: real-db



