spring:
  profiles:
    active: local

  datasource:
    url : jdbc:mariadb://database-1.cp5zb1lapca1.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: admin
    password: dev30368643
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size : 50
        show_sql : true
        format_sql : true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace

