server:
  port: 9000

spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/SPAdev
    username: dev123
    password: dev123
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size : 50
        show_sql : true
        format_sql : true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace

